### ISSUE TITLE
Missing insturctions

### ISSUE THREAD

**Issue by deckenventilator24** [COSAE-FR/ripugw#2]
After some playing around (being unfamiliar with golang) I got:

> #command-line-arguments
> svc/main.go:174:14: undefined: ServiceConfig
> svc/main.go:316:9: undefined: ServiceConfig
> svc/main.go:327:14: undefined: defaultConfigFile

and now ask myself why those types are undefined. It would be very nice if some information could be added so that it is clear to others how to use it.

Thanks.

**Comment by gaetan-rip** [comment]
ripugw is designed with our specific use cases in mind. We won't provide general support.

I think you are trying to build it on an unsupported platform (Windows ?). ripugw supports only Linux and FreeBSD (including pfSense) operating systems.

**Comment by deckenventilator24** [comment]
Thanks for your reply. I'm testing it on Ubuntu 20.04. But it was completely my bad... Due to your comment I noticed that I messed up "go run" and "go build". Issue solved. 

Thanks for your help!
